using System;
using System.IO;
using System.Text;
using UnityEditor;


namespace Library.Editor
{
    public static class PrefabsIdsGenerator
    {
        public static void WriteFile(string pathToFile, string fileNamespace, PrefabsGroup[] prefabsGroups)
        {
            var stringBuilder = new StringBuilder();
            
            stringBuilder.AppendLine("//This file is generated by PrefabsIdsGenerator");
            stringBuilder.AppendFormat($"using Library;{Environment.NewLine}{Environment.NewLine}{Environment.NewLine}");
            
            stringBuilder.Append($"namespace {fileNamespace}{Environment.NewLine}");
            stringBuilder.AppendLine("{");
            stringBuilder.AppendLine("    public static class PrefabId");
            stringBuilder.AppendLine("    {");
            
            
            foreach (var prefabsGroup in prefabsGroups)
            {
                foreach (var prefabPair in prefabsGroup.Pairs)
                {
                    stringBuilder.AppendFormat($"        [ValuesGroup(\"{prefabsGroup.Name}\")]{Environment.NewLine}");
                    var fileName = Path.GetFileNameWithoutExtension(prefabPair.AssetPath);
                    stringBuilder.AppendFormat($"        public const int {fileName} = {prefabPair.PrefabId};{Environment.NewLine}");
                }
            }
            
            stringBuilder.AppendLine("    }");
            stringBuilder.AppendLine("}");
            
            pathToFile = Path.Combine(pathToFile, "PrefabId.cs");
            
            File.WriteAllText(pathToFile, stringBuilder.ToString());              
            
            AssetDatabase.Refresh();
        }
    }
}